In [1]:
import torch 
import torch.nn.functional as F
from torch import nn

In [25]:
# CenteredLayer类要从其输入中减去均值。 要构建它，只需继承基础层类并实现前向传播功能。

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self,X):
        return X-X.mean()
    
layer=CenteredLayer()
X=torch.FloatTensor([1,2,3,4,5])# 均值为3

layer(X) # 验证是否如预期 结果为 3-每一个元素

tensor([-2., -1.,  0.,  1.,  2.])

In [26]:
# 将层作为组件合并到更复杂的模型中。

net=nn.Sequential(nn.Linear(8,128),
                 CenteredLayer()
                 )

print(net)
Y=net(torch.randn(4,8))
Y.mean()


Sequential(
  (0): Linear(in_features=8, out_features=128, bias=True)
  (1): CenteredLayer()
)


tensor(-7.4506e-09, grad_fn=<MeanBackward0>)

In [27]:
# 带参数的层 实现自定义版本的全连接层。
# 定义具有参数的层， 这些参数可以通过训练进行调整。

class MyLinear(nn.Module):
    # in_units和units，分别表示输入数和输出数。
    def __init__(self,in_units,units):
        super().__init__()
        self.weight=nn.Parameter(torch.randn(in_units,units))
        self.bias=nn.Parameter(torch.randn(units,))

        
    def forward(self,X):
        linear=torch.matmul(X,self.weight.data)+self.bias.data
        return F.relu(linear)
    
linear=MyLinear(5,3)
print(linear)
linear.weight,linear.bias

MyLinear()


(Parameter containing:
 tensor([[ 0.6522,  0.0303,  1.1214],
         [-0.0224,  1.8574,  0.3622],
         [ 1.0422, -0.3849, -0.6989],
         [-1.1314,  1.9091,  0.6286],
         [ 0.0341, -0.3816,  0.8479]], requires_grad=True),
 Parameter containing:
 tensor([ 1.1345, -0.1159,  0.5093], requires_grad=True))

In [28]:
# 自定义层直接执行前向传播计算。
linear(torch.rand(3,5))

tensor([[1.9463, 1.2882, 1.5520],
        [2.0596, 0.3962, 1.2614],
        [0.8961, 2.6895, 2.1734]])

In [35]:
# 使用自定义层构建模型，就像使用内置的全连接层一样使用自定义层
net = nn.Sequential(MyLinear(64,8),
                   MyLinear(8,1))
print(net)
X=torch.rand(2,64)
net(X)

Sequential(
  (0): MyLinear()
  (1): MyLinear()
)


tensor([[2.1738],
        [6.2272]])

- 我们可以通过基本层类设计自定义层。这允许我们定义灵活的新层，其行为与深度学习框架中的任何现有层不同。

- 在自定义层定义完成后，我们就可以在任意环境和网络架构中调用该自定义层。

- 层可以有局部参数，这些参数可以通过内置函数创建。

#### 5.5读写文件

In [40]:
# 对于单个张量，我们可以直接调用load和save函数分别读写它们。 
# 这两个函数都要求我们提供一个名称，save要求将要保存的变量作为输入
x = torch.arange(4)
torch.save(x,'x-file')
x # x的值

tensor([0, 1, 2, 3])

In [39]:
# 将存储在文件中的数据读回内存。
x2=torch.load('x-file')
x2 # 加载文件x的值

tensor([0, 1, 2, 3])

In [44]:
# 存储一个张量列表，然后把它们读回内存。
y=torch.zeros(4)
torch.save([x,y],'x-files')
y

tensor([0., 0., 0., 0.])

In [46]:
x2,y2=torch.load('x-files')
x2,y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [47]:
# 写入或读取从字符串映射到张量的字典。 当我们要读取或写入模型中的所有权重时
mydict={'x':x,'y':y}
torch.save(mydict,'mydict')
mydict

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [48]:
# 读的文件
mydict2=torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [53]:
# 加载和保存模型参数
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden=nn.Linear(20,256)
        self.output=nn.Linear(256,10)
    
    def forward(self,x):
        return self.output(F.relu(self.hidden(x)))
    
net = MLP()
print(net)
X=torch.randn(size=(2,20))
Y=net(X)
Y

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)


tensor([[-0.1293, -0.1420, -0.2753,  0.1390,  0.1589,  0.1639,  0.0121,  0.1962,
          0.0997, -0.1100],
        [ 0.1797, -0.4675,  0.0135, -0.2783,  0.1836, -0.2104, -0.1988,  0.2269,
         -0.0618,  0.1166]], grad_fn=<AddmmBackward0>)

In [54]:
# 模型的参数存储在一个叫做“mlp.params”的文件中
torch.save(net.state_dict(),'mlp.params')

In [59]:
# 加载
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [62]:
# 两个实例具有相同的模型参数，在输入相同的X时， 两个实例的计算结果应该相同
clone(X)

tensor([[-0.1293, -0.1420, -0.2753,  0.1390,  0.1589,  0.1639,  0.0121,  0.1962,
          0.0997, -0.1100],
        [ 0.1797, -0.4675,  0.0135, -0.2783,  0.1836, -0.2104, -0.1988,  0.2269,
         -0.0618,  0.1166]], grad_fn=<AddmmBackward0>)

In [61]:
clone(X)==Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

- save和load函数可用于张量对象的文件读写。

- 我们可以通过参数字典保存和加载网络的全部参数。

- 保存架构必须在代码中完成，而不是在参数中完成。